#-----------------------------------------------------------------------------
# Copyright (c) 2026 Lattice Semiconductor Corporation
#
# SPDX-License-Identifier: UNLICENSED
#
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# Variables needed by the Makefile
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# KT_APP directories
#-----------------------------------------------------------------------------
KT_APP_COMMON_DIR:=$(KT_APP_DIR)/kt_common
KT_APP_INTERACTIVE_DIR:=$(KT_APP_DIR)/kt_interactive
KT_APP_IPC_DIR:=$(KT_APP_DIR)/kt_ipc

#-----------------------------------------------------------------------------
# This header file contains the directories and file names for
# the logs and db - used jointly by Makefile and kt_app C code
#-----------------------------------------------------------------------------
KT_APP_HDR_FILE=$(KT_APP_DIR)/kt_app.h

#-----------------------------------------------------------------------------
# KT APP Simulator mode control
# - Kt App can be run in simluator mode where it does not interact with KtLib
# - It brings up the IPC server and can interact with the Python Web App
# - This is meant for development and debugging purposes
#-----------------------------------------------------------------------------
# DEFINES +=  KT_APP_SIMULATOR_MODE

export