#-----------------------------------------------------------------------------
# Copyright (c) 2026 Lattice Semiconductor Corporation
#
# SPDX-License-Identifier: UNLICENSED
#
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# Variables needed by the Makefile
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# APP related directories
#-----------------------------------------------------------------------------
APPS_OS_DIR=$(APPS_DIR)/os

KT_APP_DIR=$(APPS_DIR)/kt_app

#-----------------------------------------------------------------------------
# KT Lib directories
#-----------------------------------------------------------------------------
KT_LIB_DIR=$(KTLIB_DIR)

#-----------------------------------------------------------------------------
# OS specific tools and utils
#-----------------------------------------------------------------------------
ifeq ($(HUB_OS),linux)

# Full names of the libraries
HUB_LIB_NAME=libhub.so
KT_LIB_NAME=libktlib.so

#-----------------------------------------------------------------------------
# Toolchain and utils
#-----------------------------------------------------------------------------
CC=gcc
LD=ld
OCPY=objcopy
ODUMP=objdump
STRIP=strip
SZ=size

#-----------------------------------------------------------------------------
# toolchain flags
#-----------------------------------------------------------------------------
PRE_PROCESS_ONLY=-E -P -x c
C_OPTS = 					\
    -Wall 					\
    -Wstrict-prototypes		\
    -Wmissing-prototypes	\
    -Werror 				\
    -Winline				\
    -Werror=format-security	\
    -ffunction-sections 	\
    -fdata-sections     	\
    -fPIC

LDFLAGS =

#-----------------------------------------------------------------------------
# Toolchain related utils
#-----------------------------------------------------------------------------
ELF_TO_BIN=$(OCPY) -O binary
STRIP_ELF=$(STRIP) --strip-all
EXTRACT_DEBUG=$(OCPY) --only-keep-debug
ADD_GNU_DEBUG_LINK=$(OCPY) --add-gnu-debuglink

else

$(error Only Linux is supported)

endif

export