#-----------------------------------------------------------------------------
# Copyright (c) 2026 Lattice Semiconductor Corporation
#
# SPDX-License-Identifier: UNLICENSED
#
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# Controlling HUB debug prints
# Enable for detailed debug prints
#-----------------------------------------------------------------------------
# DEFINES += HUB_DEBUG

export